### ISSUE TITLE
Start integration testing

### ISSUE THREAD

**Issue by limpparii** [PROJ-A2022-G06-AWS-2-Cloud-Organization/PROJ-A2022-G06-AWS-2-Cloud-WebDev#115]
Add integration test to the backend side. 

Consider:
 - When these should be run?
 - What is wanted to be tested?

**Comment by limpparii** [comment]
These should be considered: 
-not able to run frontend test as there is no way of accessing backend from the frontend testing framework.
-is there need for spesific unit testing on front end or does all of it go to the scope of integration testing

**Comment by xfkoko** [comment]
Close this, new issues created based on discussion
