### ISSUE TITLE
Messages in log should be coloured

### ISSUE THREAD

**Issue by xfkoko** [PROJ-A2022-G06-AWS-2-Cloud-Organization/PROJ-A2022-G06-AWS-2-Cloud-WebDev#139]
Orange = In progress
Green = success
red = failed
black = rest

**Comment by limpparii** [comment]
This probably requires changing the log into something else than textarea. Should not be huge task to do that but logic in log needs some rework. 

https://stackoverflow.com/questions/69451247/is-there-a-way-to-have-different-colored-text-inside-a-textarea
